# Generated by Django 3.2.7 on 2021-10-04 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['date']},
        ),
    ]
